
#  Object detection  (  Vehicle Number Plate Detection )-----------------------------------------

path: C:/Users/HP/Desktop/Python/Vehicle Number plate detection dataset
train: images/train
val: images/train
test: images/train

names:
  0: Number plate

